server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/**
          # Remove filters section completely

        - id: document-tracking
          uri: lb://DOCUMENT-TRACKING
          predicates:
            - Path=/document/**
          # No filters needed for now

        - id: version_tracking
          uri: lb://VERSION-TRACKING
          predicates:
            - Path=/document/**
          # Remove filters section completely

      discovery:
        locator:
          enabled: false
          lower-case-service-id: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka